### ISSUE TITLE
conversion issue genind objects

### ISSUE THREAD

**Issue by juance100** [emmanuelparadis/pegas#12]
A similar issue as #10 occurs after a conversion of df to genind.

First I converted nancycats into a data.frame

> nancydf <- genind2df(nancycats, sep="/")

Then I imported the same data into a genind object:

> nancycats2 <- df2genind(nancydf[,2:10], sep="/", ncode=3, ploidy=2, pop= nancydf$pop)

When applying hw.test to this genind object that contains the same information as the original nancycats a warning() is retrieved and the Chisquare estimation shows errors

> hw.test(nancycats2)
>             chi^2  df  Pr(chi^2 >) Pr.exact
> fca8  46504.45655 120 0.000000e+00        0
> fca23  2023.71668  55 0.000000e+00        0
> fca43  7957.23992  45 0.000000e+00        0
> fca45    93.25975  36 5.681616e-07        0
> fca77 21636.11122  66 0.000000e+00        0
> fca78  1072.03868  28 0.000000e+00        0
> fca90 11361.25571  66 0.000000e+00        0
> fca96   825.46134  66 0.000000e+00        0
> fca37  2283.46490 153 0.000000e+00        0
> There were 18 warnings (use warnings() to see them)

**Comment by emmanuelparadis** [comment]
I repeated your code and got identical results. I guess the various modifications in pegas and adegenet have solved this issue.
