### ISSUE TITLE
NAs in loci2genind "." treated as an allele

### ISSUE THREAD

**Issue by thibautjombart** [emmanuelparadis/pegas#14]
I have come across this trying to solve (https://github.com/thibautjombart/adegenet/issues/101). 
I am not sure if "." is sometimes a character in `loci` objects, but during the conversion to `genind` these should probably be treated as NAs.

Reproducible example: 

``` r
> tab(loci2genind(as.loci("a/A")))
  loc1.A loc1.a
1      1      1
> tab(loci2genind(as.loci(c("a/A","./."))))
  loc1.A loc1.a loc1..
1      1      1      0
2      0      0      2
> 
```

**Comment by emmanuelparadis** [comment]
Thanks. Fixed.
