### ISSUE TITLE
error message with theta.msat

### ISSUE THREAD

**Issue by kathfi** [emmanuelparadis/pegas#16]
Dear all,

I am using "theta.msat" to estimate Theta from some microsatellite data. I load the data in genepop format using the read.genepop command, which works fine. However, when I try estimating theta, I always get this error message:

Error in x$allele : $ operator is invalid for atomic vectors

I am not sure what this means and how to fix this, and wonder if someone can help me overcome this?

many thanks in advance

**Comment by emmanuelparadis** [comment]
You have to convert as a "loci" object before using functions in pegas:

x <- as.loci(..
theta.msat(x)

**Comment by kathfi** [comment]
thanks a lot, it works now!

**Comment by kathfi** [comment]
Dear Emmanuel Paradis,

may I ask another question? hence conducting the calculation, I get widely varying Theta estimates (between 200 and 8) between the three methods implemented for microsat loci - which all seem unrealistic (for comparison, Theta estimated according to  Chakraborty and Weiss (1991)'s method yielded ca. 2)

Is there anything else inherent to the program I have to take into account for the calculation? 
The data were in structure format, alleles coded in 3 digits.

many thanks

**Comment by emmanuelparadis** [comment]
Yes I had similar (i.e., a bit weird) results with other data. I suppose this is more a problem with the method(s). That said, it is a bit logical to obtain large values of Theta with micro-sat considering that these loci tend to mutate faster than others. I think it'd be necessary to dig a bit more the methods to understand what's going there.

**Comment by kathfi** [comment]
thank you for the answer. I agree to expect higher Theta values, however not in the range as I did when using this method. I will follow your advice and look more into it.
