### ISSUE TITLE
error message with theta.msat 

### ISSUE THREAD

**Issue by kathfi** [emmanuelparadis/pegas#17]
Dear Emmanuel Paradis,

may I ask another question regarding the thread "error message with theta.msat"? Hence conducting the calculation, I get widely varying Theta estimates (between 200 and 8) between the three methods implemented for microsat loci - which all seem unrealistic (for comparison, Theta estimated according to Chakraborty and Weiss (1991)'s method yielded ca. 2)

Is there anything else inherent to the program I have to take into account for the calculation?
The data were in structure format, alleles coded in 3 digits.

many thanks

**Comment by emmanuelparadis** [comment]
closed as #16
