### ISSUE TITLE
P values absent in some AMOVA runs with hierarchical levels

### ISSUE THREAD

**Issue by CEMoffat** [emmanuelparadis/pegas#18]
I am wondering why I do not consistently get p values for all levels in a hierarchical AMOVA in pegas.

When I run the AMOVA on the same dataset, but with a different number of categories (sites) in my second factor, I get a p value only for the first hierarchical level (hosts) with the higher number of sites.
Would I be correct in assuming if the p value is not shown, p<0.001?

Many thanks for any insight.

My markdown document is attached, not sure why it is not just showing. I will try to fix this. But you can see the analyses in the PDF. 

[test_amova_markdown.pdf](https://github.com/emmanuelparadis/pegas/files/138368/test_amova_markdown.pdf)

**Comment by emmanuelparadis** [comment]
Thanks for the detailed report. The absent P-value is because it is NA. Prabably, one of the permutations failed and returned NA (probably because there are only 2 categories of hosts). Maybe you can repeat the analysis with nperm = 100 to see if you get a P-value.

**Comment by CEMoffat** [comment]
Thanks, that did work! What is even stranger (or maybe not) is that after I tried nperm=100, I repeated with nperm=1000 and for the first time I got a P-value. Problem solved!
