### ISSUE TITLE
loci2genind and ploidy level?

### ISSUE THREAD

**Issue by jgx65** [emmanuelparadis/pegas#21]
It seems that by default, a ploidy level of 2 is reported in loci2genind.  

``` r
yc<-read.vcf("chrY.vcf.gz",1,100) #haploid data from human y chrom
gi.yc<-loci2genind(yc)
ploidy(gi.yc)
```

Any clues?

**Comment by emmanuelparadis** [comment]
Yes: ploidy was always set to 2 (the default of df2genind). The definition of this function is now:

``` r
loci2genind(x, ploidy = getPloidy(x)[1])
```

Now on GH. Thanks!

**Comment by emmanuelparadis** [comment]
I've just changed it to:

``` r
loci2genind(x, ploidy = getPloidy(x))
```

**Comment by jgx65** [comment]
Perfect, thanks!
