### ISSUE TITLE
Error when using haploNet(h) on Fasta file.

### ISSUE THREAD

**Issue by jorgeamaya** [emmanuelparadis/pegas#22]
Hi!

I'm trying to use pegas to obtain an haplotype network from a multifasta file, but I'm getting the following error:

`library(pegas)`
`input <- "myalignment.fasta"`
`d <- ape::read.dna(input, format='fasta')`
`h <- pegas::haplotype(d)`
`net <- pegas::haploNet(h)`
`Error in integrate(L_jm, 0, 1, j = i, m = M) : non-finite function value` 

This is weird since the example in the documentation, using the woodmouse dataset, works OK in my computer. I have checked my fasta file too and everything seems to be in order (correct number of sequences, all of the same length, etc). I also tried reducing the number of sequences in my file to rule out I was exhausting the RAM but to no avail. Where does this error come from? Should I change the way I upload the fasta file?

**Comment by emmanuelparadis** [comment]
Hi,

This happens sometimes that the associated probabilities cannot be calculated. I need to dig into this when I have time. If you don't need these probabilities (I guess most people don't), use the option getProb = FALSE of haploNet().
