### ISSUE TITLE
unexpected behavior when trying to install pegas with githubinstall()

### ISSUE THREAD

**Issue by vinsondoyle** [emmanuelparadis/pegas#23]
## githubinstall("pegas") installs an old version of pegas from the repository of dwinter:
`githubinstall("pegas")`
Suggestion:
 - dwinter/Pegas  My branch of Emmanuel Paradis' PEGAS library for phylogeography/popgen
Do you want to install the package (Y/n)?  y
Downloading GitHub repo dwinter/Pegas@master
from URL https://api.github.com/repos/dwinter/Pegas/zipball/master
Installing pegas
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/nv/tb992mxd3hjd8bm6ylk3plf80000gn/T/RtmpgCLwQG/devtools24646f424d1d/dwinter-Pegas-87dafe2'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library' --install-tests 

* installing *source* package ‘pegas’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (pegas)

## githubinstall("emmanuelparadis/pegas/pegas"), strangely, installs an R package to retrieve trading prices and other data from the Australian Energy Market Operator. Not too useful for genetic data!
`githubinstall("emmanuelparadis/pegas/pegas")`
Suggestion:
 - imanuelcostigan/aemo  Get price and demand data from AEMO website
Do you want to install the package (Y/n)?  y
Downloading GitHub repo imanuelcostigan/aemo@master
from URL https://api.github.com/repos/imanuelcostigan/aemo/zipball/master
Installing aemo
trying URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/lubridate_1.6.0.tgz'
Content type 'application/x-gzip' length 642955 bytes (627 KB)
==================================================
downloaded 627 KB

Installing lubridate
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/nv/tb992mxd3hjd8bm6ylk3plf80000gn/T/RtmpgCLwQG/devtools246469d6e5a/lubridate'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library' --install-tests 

* installing *binary* package ‘lubridate’ ...
* DONE (lubridate)
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/nv/tb992mxd3hjd8bm6ylk3plf80000gn/T/RtmpgCLwQG/devtools24643cf728e3/imanuelcostigan-aemo-7833efa'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library' --install-tests 

* installing *source* package ‘aemo’ ...
** R
** data
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (aemo)

**Comment by zkamvar** [comment]
IMO, this is not a bug with pegas, but rather a bug (or perhaps a feature!) of whatever package supplies the function `githubinstall()`. Based on my google search, I think it's this one? https://github.com/hoxo-m/githubinstall

If it is, your issue is probably best fielded there.

**Comment by vinsondoyle** [comment]
Thanks for the feedback. I will post it there.

After resolving a gcc compiler issue on my computer, I was able to install pegas from a local version of the repository. I tried using githubinstall() as a work around since it works well for other packages. I thought it might be of interest to the developers of pegas.

**Comment by emmanuelparadis** [comment]
Thanks! I guess that's solved.
