### ISSUE TITLE
pop function exported in hw.test?

### ISSUE THREAD

**Issue by EricArcher** [emmanuelparadis/pegas#24]
I've had a user of another package report this error : 

`Error in pop(x) : could not find function "pop"`

I've traced this to a call to `pegas::hw.test.genind` being made through my `strataG` package. I import `hw.test`, but not the entire `pegas` package. Can you tell me if the `adegenet::pop` function is imported in hw.test? I'm assuming that it isn't given this second line:

`pop <- NULL`

If that is true, is it possible to modify so that pop is imported from `adegenet`?

**Comment by emmanuelparadis** [comment]
Yes this could be added. Although it seems from the code of `hw.test.genind` that `pop` is never used since `byPop` is always FALSE. So this bits of code could be removed? @thibautjombart any idea/suggestion?

**Comment by thibautjombart** [comment]
My two cents is use `adegenet::pop`; I find `pkg::foo` quite useful in packages as it simplifies imports, and the code itself is explicit about what comes from where.

**Comment by emmanuelparadis** [comment]
Good! Anyway, `pop` being unused there, I'll simplify the code by commenting out these bits. Thibaut: you were thinking to use them later?

**Comment by thibautjombart** [comment]
I honestly don't remember, but if there are bits that are not used, feel free to get rid of them. Whatever needs adding can always be re-added later ;)

**Comment by emmanuelparadis** [comment]
Done. Just pushed version 0.10-2 of pegas on GH.
Thanks.
