### ISSUE TITLE
Session crash when loading vcf file with ~

### ISSUE THREAD

**Issue by frederic-michaud** [emmanuelparadis/pegas#28]
Hi,

I noticed that if I try to open a file with a relative path from my home, the R session crash:

```
> read.vcf("~/example2.vcf")
File apparently not yet accessed:
Scanning file ~/example2.vcf 

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .Call(read_bin_pegas, file, chunck.size, scanned)
 2: VCFloci(file, what = "POS", quiet = quiet)
 3: read.vcf("~/example2.vcf")
```

This can be backtrace to two things:

1. The function _f <- .VCFconnection(file)_ correctly identify the file as existing and a correct VCF file.
2. The c function  _fl = fopen(filename, "r");_ from _readVCFbin.c_ cannot read path starting with a "~".

Indeed, usually, if the file does not exist, the user is nicely notified by the first function. In this case, R can access the file but not c, resulting in the segfault and ultimately in the crash of the R session (on Rstudio at least). 

I guess that a simple fix would probably be to use [exand](https://stat.ethz.ch/R-manual/R-devel/library/base/html/path.expand.html) at the beggining of the function _read.vcf(file, from = 1, to = 1e4, which.loci = NULL, quiet = FALSE)_. I can write a PR if needed. 

Cheers!

**Comment by zkamvar** [comment]
The solution would be to add expand.path or normalize.path on the R side.

**Comment by emmanuelparadis** [comment]
Thanks! Apparently it's not a problem on Linux.
