### ISSUE TITLE
haploNet

### ISSUE THREAD

**Issue by jhmarcus** [emmanuelparadis/pegas#3]
Dear Emmanuel,

I can't seem to get haploNet working for plotting up a haplotype network. For instance following the example provided in the read.dna help ...

``` R
library(pegas)

cat(">No305",
    "NTTCGAAAAACACACCCACTACTAAAANTTATCAGTCACT",
    ">No304",
    "ATTCGAAAAACACACCCACTACTAAAAATTATCAACCACT",
    ">No306",
    "ATTCGAAAAACACACCCACTACTAAAAATTATCAATCACT",
    file = "exdna.txt", sep = "\n")
x <- read.dna("exdna.txt", format = "fasta")
h <- haplotype(x)
net <- haploNet(h)
```

it returns this error 

```
Error in numeric(max(j)) : vector size cannot be infinite
In addition: Warning message:
In max(j) : no non-missing arguments to max; returning -Inf
```

Also is it possible to create a haplotype network from the haplotype.loci class. It would be great to be able to use read.loci and / or read.vcf for doing this. Any information / help would be greatly appreciated.

Best,

Joe

**Comment by emmanuelparadis** [comment]
Hi Joseph,

Thanks for reporting this. The bug happens because with this small toy example there is no alternative link in the network. This is fixed. With real data, there'll certainly be alternative links, so this won't likely happen.

No it's not (yet) possible to create a haplotype network from the "haplotype.loci" class, but it's on the list of TODOs.

Cheers,

Emmanuel

**Comment by jhmarcus** [comment]
Hey Emmanuel,

Great! Thank you for the prompt reply. 

Best,

Joe

**Comment by jhmarcus** [comment]
Hey Emmanuel,

One more quick question if you don't mind. Is there an easy way to filter out haplotypes by frequency before creating a haploNet object? That would be very helpful for plotting up real data. Thank you!

Best,

Joe

**Comment by emmanuelparadis** [comment]
Hi Joseph,

Good question. For the moment, there's no easy way to do it (only the usual "easy-if-you-know-well-R"). To ease tracking of these discussions, I'm creating separate issues with your very good suggestions and am closing this one.

Cheers,

Emmanuel
