### ISSUE TITLE
First P value missing for hierarchical AMOVA with 2 or more tiers [new]

### ISSUE THREAD

**Issue by ghost** [emmanuelparadis/pegas#33]
Hi Emmanuel, 
I'm running into trouble with Pegas's AMOVA function when I run more than one hierarchical level on my data, where I end up not  getting a P value for the highest hierarchical level in AMOVAs with more than one level. A similar complaint is listed as a 'resolved issue', however, I believe my problem is unique. 

**What I did**

First I input a matrix of distances between individuals and convert it
to the distance matrix class Second, I create the factors (provinces and
sites within provinces) Then I run the AMOVA (code shown below)

    library(pegas)
    geneticmatrix <- read.delim("rouss_matrix-new.txt", header = FALSE)
    distmatrix <- as.dist(geneticmatrix)
    provinces <- factor(c(rep("Sel", 14), rep("Joh", 41), rep("Per", 6), rep("Pah", 45)))
    sites <- factor(c(rep("TDJ", 8), rep("HKL", 6), rep("Joh", 41), rep("Per", 6), 
                        rep("P1", 7), rep("P2", 8), rep("P3", 9), rep("P4", 8), 
                        rep("P5", 6), rep("P6", 7)))

    amovatest <- amova(distmatrix ~ provinces/sites)
    amovatest

    ## 
    ##  Analysis of Molecular Variance
    ## 
    ## Call: amova(formula = distmatrix ~ provinces/sites)
    ## 
    ##                 SSD        MSD  df
    ## provinces 0.6259918 0.20866394   3
    ## sites     0.2987738 0.04979563   6
    ## Error     4.0503148 0.04219078  96
    ## Total     4.9750803 0.04738172 105
    ## 
    ## Variance components:
    ##              sigma2 P.value
    ## provinces 0.0066337        
    ## sites     0.0010315  0.5145
    ## Error     0.0421908        
    ## 
    ## Variance coefficients:
    ##         a         b         c 
    ##  7.372487 13.795907 22.949686

As can be seen above, the P value for the provinces level is missing.
You have pointed out elsewhere that this is because the function is
returning an NA for this P. However, the function consistently failed to
return the P with repeated runnings and reduced permutations.

I looked into the code, and this seems to happen the following way:

**1.** The function creates the dataframe gr with provinces in first
column, sites in second

    gr

    ##     provinces sites
    ## 1         Sel   TDJ
    ## 2         Sel   TDJ
    ## 3         Sel   TDJ
    ## 4         Sel   TDJ
    ## 5         Sel   TDJ
    ## 6         Sel   TDJ
    ## 7         Sel   TDJ
    ## 8         Sel   TDJ
    ## 9         Sel   HKL
    ## 10        Sel   HKL
    ## 11        Sel   HKL
    ## 12        Sel   HKL
    ## 13        Sel   HKL
    ## 14        Sel   HKL
    ## 15        Joh   Joh
    ## 16        Joh   Joh
    ## 17        Joh   Joh
    ## 18        Joh   Joh
    ## 19        Joh   Joh
    ## 20        Joh   Joh
    ## 21        Joh   Joh
    ## 22        Joh   Joh
    ## 23        Joh   Joh
    ## 24        Joh   Joh
    ## 25        Joh   Joh
    ## 26        Joh   Joh
    ## 27        Joh   Joh
    ## 28        Joh   Joh
    ## 29        Joh   Joh
    ## 30        Joh   Joh
    ## 31        Joh   Joh
    ## 32        Joh   Joh
    ## 33        Joh   Joh
    ## 34        Joh   Joh
    ## 35        Joh   Joh
    ## 36        Joh   Joh
    ## 37        Joh   Joh
    ## 38        Joh   Joh
    ## 39        Joh   Joh
    ## 40        Joh   Joh
    ## 41        Joh   Joh
    ## 42        Joh   Joh
    ## 43        Joh   Joh
    ## 44        Joh   Joh
    ## 45        Joh   Joh
    ## 46        Joh   Joh
    ## 47        Joh   Joh
    ## 48        Joh   Joh
    ## 49        Joh   Joh
    ## 50        Joh   Joh
    ## 51        Joh   Joh
    ## 52        Joh   Joh
    ## 53        Joh   Joh
    ## 54        Joh   Joh
    ## 55        Joh   Joh
    ## 56        Per   Per
    ## 57        Per   Per
    ## 58        Per   Per
    ## 59        Per   Per
    ## 60        Per   Per
    ## 61        Per   Per
    ## 62        Pah    P1
    ## 63        Pah    P1
    ## 64        Pah    P1
    ## 65        Pah    P1
    ## 66        Pah    P1
    ## 67        Pah    P1
    ## 68        Pah    P1
    ## 69        Pah    P2
    ## 70        Pah    P2
    ## 71        Pah    P2
    ## 72        Pah    P2
    ## 73        Pah    P2
    ## 74        Pah    P2
    ## 75        Pah    P2
    ## 76        Pah    P2
    ## 77        Pah    P3
    ## 78        Pah    P3
    ## 79        Pah    P3
    ## 80        Pah    P3
    ## 81        Pah    P3
    ## 82        Pah    P3
    ## 83        Pah    P3
    ## 84        Pah    P3
    ## 85        Pah    P3
    ## 86        Pah    P4
    ## 87        Pah    P4
    ## 88        Pah    P4
    ## 89        Pah    P4
    ## 90        Pah    P4
    ## 91        Pah    P4
    ## 92        Pah    P4
    ## 93        Pah    P4
    ## 94        Pah    P5
    ## 95        Pah    P5
    ## 96        Pah    P5
    ## 97        Pah    P5
    ## 98        Pah    P5
    ## 99        Pah    P5
    ## 100       Pah    P6
    ## 101       Pah    P6
    ## 102       Pah    P6
    ## 103       Pah    P6
    ## 104       Pah    P6
    ## 105       Pah    P6
    ## 106       Pah    P6

**2.** N is created to represent number of individuals per group

    N <- lapply(gr, tabulate)
    N

    ## $provinces
    ## [1] 41 45  6 14
    ## 
    ## $sites
    ##  [1]  6 41  7  8  9  8  6  7  6  8

The problem that creeps in here is that the tabulate function actually
reorders the factors. This doesn't matter immediately, as N is not yet
being used for anything that requires the order to be preserved...

The problem is in the Nlv &gt; 1 code block. (only used for hierarchical
AMOVAs) It occurs we reach the section you've labeled "for the highest
level permute the one below".

    N2 <- N[[2]]
    N2

    ##  [1]  6 41  7  8  9  8  6  7  6  8

    Higr <- gr[, 1][cumsum(N2)]
    Higr

    ##  [1] Sel Joh Joh Pah Pah Pah Pah Pah Pah Pah
    ## Levels: Joh Pah Per Sel

The code's use of cumsum assumes that the order of the tabulated counts
of "sites" in N2 still line up with the initial order of "provinces"
found in gr. Except that they don't.

The result is that if tabulate reorders the factors, there is every
chance that (a) the factors of the lower level are being incorrectly
paired with those of the upper level(which has actually happened in that
data), and (b) as a biproduct, in a set such as the above with only a
few individuals in some of the 'top-tier' factors, one of the province
factors is being left out altogether.

Thus, when we do the following in any permutation,

    rGR[,1] <- unlist(mapply(rep, sample(Higr), each = N2, SIMPLIFY = FALSE))
    rGR

    ##     provinces sites
    ## 1         Pah   TDJ
    ## 2         Pah   TDJ
    ## 3         Pah   TDJ
    ## 4         Pah   TDJ
    ## 5         Pah   TDJ
    ## 6         Pah   TDJ
    ## 7         Pah   TDJ
    ## 8         Pah   TDJ
    ## 9         Pah   HKL
    ## 10        Pah   HKL
    ## 11        Pah   HKL
    ## 12        Pah   HKL
    ## 13        Pah   HKL
    ## 14        Pah   HKL
    ## 15        Pah   Joh
    ## 16        Pah   Joh
    ## 17        Pah   Joh
    ## 18        Pah   Joh
    ## 19        Pah   Joh
    ## 20        Pah   Joh
    ## 21        Pah   Joh
    ## 22        Pah   Joh
    ## 23        Pah   Joh
    ## 24        Pah   Joh
    ## 25        Pah   Joh
    ## 26        Pah   Joh
    ## 27        Pah   Joh
    ## 28        Pah   Joh
    ## 29        Pah   Joh
    ## 30        Pah   Joh
    ## 31        Pah   Joh
    ## 32        Pah   Joh
    ## 33        Pah   Joh
    ## 34        Pah   Joh
    ## 35        Pah   Joh
    ## 36        Pah   Joh
    ## 37        Pah   Joh
    ## 38        Pah   Joh
    ## 39        Pah   Joh
    ## 40        Pah   Joh
    ## 41        Pah   Joh
    ## 42        Pah   Joh
    ## 43        Pah   Joh
    ## 44        Pah   Joh
    ## 45        Pah   Joh
    ## 46        Pah   Joh
    ## 47        Pah   Joh
    ## 48        Pah   Joh
    ## 49        Pah   Joh
    ## 50        Pah   Joh
    ## 51        Pah   Joh
    ## 52        Pah   Joh
    ## 53        Pah   Joh
    ## 54        Pah   Joh
    ## 55        Sel   Joh
    ## 56        Sel   Per
    ## 57        Sel   Per
    ## 58        Sel   Per
    ## 59        Sel   Per
    ## 60        Sel   Per
    ## 61        Sel   Per
    ## 62        Sel    P1
    ## 63        Pah    P1
    ## 64        Pah    P1
    ## 65        Pah    P1
    ## 66        Pah    P1
    ## 67        Pah    P1
    ## 68        Pah    P1
    ## 69        Pah    P2
    ## 70        Pah    P2
    ## 71        Pah    P2
    ## 72        Pah    P2
    ## 73        Pah    P2
    ## 74        Pah    P2
    ## 75        Pah    P2
    ## 76        Pah    P2
    ## 77        Pah    P3
    ## 78        Pah    P3
    ## 79        Pah    P3
    ## 80        Pah    P3
    ## 81        Pah    P3
    ## 82        Pah    P3
    ## 83        Pah    P3
    ## 84        Pah    P3
    ## 85        Pah    P3
    ## 86        Pah    P4
    ## 87        Pah    P4
    ## 88        Pah    P4
    ## 89        Pah    P4
    ## 90        Pah    P4
    ## 91        Pah    P4
    ## 92        Pah    P4
    ## 93        Joh    P4
    ## 94        Joh    P5
    ## 95        Joh    P5
    ## 96        Joh    P5
    ## 97        Joh    P5
    ## 98        Joh    P5
    ## 99        Joh    P5
    ## 100       Joh    P6
    ## 101       Joh    P6
    ## 102       Joh    P6
    ## 103       Joh    P6
    ## 104       Joh    P6
    ## 105       Joh    P6
    ## 106       Joh    P6

We get a dataframe where (a) there are differing amounts of each
province factor, and (b) the Per factor has dropped out altogether.

Thus, when we (for each iteration) we getNcoefficient, we reach the
expression,

A &lt;- sum(foo(Nig2, g)/foo(Nig, g))

This combines these two functions:

    foo(Nig2, g)

    ##  Joh  Pah  Per  Sel 
    ##   64 2032   64    0

    foo(Nig, g)

    ## Joh Pah Per Sel 
    ##   8  90   8   0

But since both are empty for Perlis, when we divide them to produce A
(as above), we get:

    A <- sum(foo(Nig2, g)/foo(Nig, g))
    A

    ## [1] NaN

As a result, the overall value returned by getNcoefficient for a typical
i is

    rNcoef <- getNcoefficient(rGR, Nlv, rN, n)
    rNcoef

    ##        a        b        c 
    ##      NaN      NaN 14.14465

Leading to (e.g.)

    rSigma2test <- matrix(0, 1, length(sigma2))
    rSigma2test[1, 1] <- getVarComp(rSSD/rDF, Nlv, rNcoef)[1]
    rSigma2test

    ##      [,1] [,2] [,3]
    ## [1,]  NaN    0    0

(only 1st spot significant)

So, the return of the overall series of permutations is

                for (i in 1:nperm) {
                    rGR[, 1] <- unlist(mapply(rep, sample(Higr), 
                      each = N2, SIMPLIFY = FALSE))
                    rN <- lapply(rGR, tabulate)
                    rSSD <- getSSD(rY, rGR, Nlv, rN, n)
                    rDF <- getDF(rGR, Nlv, rN, n)
                    rNcoef <- getNcoefficient(rGR, Nlv, rN, n)
                    rSigma2[i, 1] <- getVarComp(rSSD/rDF, Nlv, rNcoef)[1]
                }
    head(rSigma2)

    ##      [,1]         [,2] [,3]
    ## [1,]  NaN  0.002114401    0
    ## [2,]  NaN  0.002598085    0
    ## [3,]  NaN -0.002780967    0
    ## [4,]  NaN  0.002669193    0
    ## [5,]  NaN -0.001592374    0
    ## [6,]  NaN  0.001975109    0

Finally, when we construct the P values:

    P <- numeric(Nlv + 1)
            for (j in 1:(Nlv + 1)) P[j] <- sum(rSigma2[, j] >= sigma2[j])/(nperm + 
                1)
            P[Nlv + 1] <- NA
    P

    ## [1]        NA 0.5374625        NA

Where sum/(nperm+1) returns NA and is assigned to the first slot.

**My current workaround**

At the moment I've edited the overall AMOVA function (only for the
2-tier case; not higher) to allow the inclusion of a numeric vector
exactly paralleling the second factor. (as argument 'lev2')

    amova_twotier_fixed <- function (formula, lev2 , data = NULL, nperm = 1000, is.squared = FALSE)
    lev2 <- c(8, 6, 41, 6, 7, 8, 9, 8, 6, 7)

I allow the function to proceed as normal, but when it comes time to set
N2 during permutations, I substitute

    
    N2 <- lev2

which has the same form as N\[\[2\]\], except a guaranteed order.

This seems to fix the problem. Thus,

    amova_twotier_fixed(distmatrix ~ provinces/sites, lev2 = lev2)

    ## 
    ##  Analysis of Molecular Variance
    ## 
    ## Call: amova_twotier_fixed(formula = distmatrix ~ provinces/sites, lev2 = lev2)
    ## 
    ##                 SSD        MSD  df
    ## provinces 0.6259918 0.20866394   3
    ## sites     0.2987738 0.04979563   6
    ## Error     4.0503148 0.04219078  96
    ## Total     4.9750803 0.04738172 105
    ## 
    ## Variance components:
    ##              sigma2 P.value
    ## provinces 0.0066337  0.0719
    ## sites     0.0010315  0.5504
    ## Error     0.0421908        
    ## 
    ## Variance coefficients:
    ##         a         b         c 
    ##  7.372487 13.795907 22.949686

The solution would possibly also work for higher-level AMOVAs, as the
offending line always applies to the highest level, and 'lev2' could be
substituted for the penultimate level every time... (haven't checked for
further issues in the Nlv &gt; 2 section, though)...

It is a rather clumsy solution, though.

Thought I'd bring the issue to your attention all the same in case you
would like to come up with a more seamless patch.

Regards, 

Moshe Jasper

**Comment by emmanuelparadis** [comment]
Hi Moshe,

Thanks for the very detailed report. I'll have a close look at it.

Emmanuel

**Comment by emmanuelparadis** [comment]
Hi Moshe,

I 've just pushed a new version of pegas (0.10-6) on GH which hopefully fixes this.

The observations need indeed to be arranged in a "block" way for the permutations to work (the rest of the calculations are not affected), and the reordering is now done inside the function.

Cheers,

Emmanuel
