### ISSUE TITLE
hw.test fails if a locus contains all missing data

### ISSUE THREAD

**Issue by zkamvar** [emmanuelparadis/pegas#36]
With the recent version of pegas, code that used to work with hw.test() now fails:

``` r
library(adegenet)
library(pegas)
data(nancycats)
n17 <- nancycats[pop = 17, drop = FALSE]
hw.test(n17)
#> Warning in hw.test.loci(x = x, B = B, ...): The following loci were dropped (not the same ploidy for all individuals):
#> fca45
#> Warning in mapply(test.polyploid, y, ploidy = ploidy): longer argument not
#> a multiple of length of shorter
#> Error in dimnames(ans) <- list(names(y), c("chi^2", "df", "Pr(chi^2 >)")): length of 'dimnames' [1] not equal to array extent
```

Created on 2018-08-17 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

The expected output was this:

```
##           chi^2 df Pr(chi^2 >)
## fca8  22.100000 15   0.1052085
## fca23 10.631111 10   0.3869703
## fca43 22.071111 10   0.0147464
## fca45        NA NA          NA
## fca77 24.180000 21   0.2844190
## fca78  1.764543  3   0.6226810
## fca90  6.686359  6   0.3508286
## fca96  0.312500  1   0.5761501
## fca37  5.097337  3   0.1648068
```

**Comment by emmanuelparadis** [comment]
Fixed. Thanks for the report. Note that the output is now different: the row with 'fca45' is dropped (as reported by the warning message).

**Comment by zkamvar** [comment]
I do have a question, though: is it necessary to force dropping the loci? Is it possible to add a `drop` argument to the function (default to `TRUE`) so that the user can choose whether or not they want this behavior?

**Comment by zkamvar** [comment]
Also, the warning message is not at all clear since the issue is missing data as opposed to ploidy

**Comment by emmanuelparadis** [comment]
You are doubly right. I have changed the code so the output is similar to what you posted (should make comparisons of different analyses easier), and the warning message is now:

```r
Warning message:
In z(a, B = 0) : The following locus was ignored: fca45
(not the same ploidy for all individuals, or too many missing data)

```

**Comment by zkamvar** [comment]
Thank you! This helps a lot!

one more thing, a new spurious warning has appeared:

```
> hw.test(n17)
          chi^2 df Pr(chi^2 >) Pr.exact
fca8  22.100000 15   0.1052085    0.180
fca23 10.631111 10   0.3869703    0.299
fca43 22.071111 10   0.0147464    0.060
fca45        NA NA          NA       NA
fca77 24.180000 21   0.2844190    0.185
fca78  1.764543  3   0.6226810    1.000
fca90  6.686359  6   0.3508286    0.176
fca96  0.312500  1   0.5761501    1.000
fca37  5.097337  3   0.1648068    0.239
Warning messages:
1: In hw.test.loci(x = x, B = B, ...) :
  The following locus was ignored: fca45
(not the same ploidy for all individuals, or too many missing data)
2: In (function (x, ploidy)  :
  no Monte Carlo test available for polyploids
```

This will confuse users who do not have polyploid data.

**Comment by emmanuelparadis** [comment]
I've changed the message to: "Monte Carlo test available only if all individuals are diploid"

**Comment by zkamvar** [comment]
But in this case, all individuals are diploid. The only issue is that there
are missing data.

**Comment by emmanuelparadis** [comment]
... and all individuals have `NA` for this locus. Suppose there is a mix of ploidy level for a locus and all non-diploid individuals are not genotyped (i.e., have `NA`), then the MC test will run. So a more exact message would be: "Monte Carlo test available only if all genotyped individuals are diploid".
