### ISSUE TITLE
some functions not installed

### ISSUE THREAD

**Issue by willyard** [emmanuelparadis/pegas#39]
I installed pegas on my Windows 7 PC today and loaded this library in R 3.2.2. I can see from the library help that pegas vers. 0.9 has been loaded. However, many functions, including mjn, are not listed. 

After confirming that pegas has been loaded, and in response to the sample command: 
mjn(dat, epsilon = 0, max.n.cost = 10000, prefix = "median.vector_")
I receive: 
Error: could not find function "mjn".

Sorry to trouble you with this, but I do not know how else to install or load the library to get these functions.
Thanks so much
--Ann

**Comment by emmanuelparadis** [comment]
Install the current version of pegas (0.11): `mjn` was introduced in pegas 0.10.

Best,
