### ISSUE TITLE
read.loci() silently deleting samples on import

### ISSUE THREAD

**Issue by emmanuelparadis** [emmanuelparadis/pegas#40]
Follow-up from [this](https://github.com/thibautjombart/adegenet/issues/253).

@barretp: you could try:

```r
x <- read.csv(".....", row.names = 1)
x <- as.loci(x, col.loci = 26:42, col.pop = 2)
```

**Comment by barretp** [comment]
Thanks, Emmanuel! This works as a temporary fix, but obviously the most concerning part is that there is no warning that the samples are dropped. With a large dataset it's easy not to notice that a few are missing. :/

**Comment by emmanuelparadis** [comment]
Have you tried `read.loci()` but without the option `row.names = 1`? Since `header = TRUE`, the first column should be taken as row names by default.

**Comment by barretp** [comment]
Yes, same problem. Still dropping ~70 samples.

**Comment by emmanuelparadis** [comment]
Can you send me (privately) your data? There's something wrong in `read.loci()` but this function calls `read.table(, sel = loci.sep)` and then `as.loci()`, so it's not clear where is the problem.

**Comment by emmanuelparadis** [comment]
The issue is that some entries in your file have an apostrophe, so the data are read but creating a very long character string between two apostrophes (which are in fact interpreted as single quotes). That's why there is no error. You can get your data in pegas correctly with:

```r
read.loci(......, quote = "")
```
