### ISSUE TITLE
MMD documentation typo help?

### ISSUE THREAD

**Issue by aeberardi** [emmanuelparadis/pegas#42]
https://github.com/emmanuelparadis/pegas/blob/7eb3b60473016f1b003a380a4151cb5769f50633/pegas/man/MMD.Rd#L28

Hi there, we were wondering if you could clarify what you mean in the description of MMD function : "The histogram shows the observed distribution of pairwise distances. The lines show an empirical density estimate (in blue) and the expected distribution under stable **population population** (Rogers and Harpending 1992)."

Thanks a lot!

**Comment by emmanuelparadis** [comment]
Hi. Thanks for spotting the typo.This should be simply "stable population".
