### ISSUE TITLE
filter out haplotypes by frequency

### ISSUE THREAD

**Issue by emmanuelparadis** [emmanuelparadis/pegas#5]
Suggestion from @jhmarcus: filter out haplotypes by frequency before creating a haploNet object. Currently, it's possible but not so easy.

**Comment by emmanuelparadis** [comment]
Here's a function using the generic `subset`:

``` r
subset.haplotype <- function(x, freqmin = 1, freqmax = Inf, ...)
{
    oc <- oldClass(x)
    idx <- attr(x, "index")
    f <- sapply(idx, length)
    s <- f <= freqmax & f >= freqmin
    x <- x[s, ]
    attr(x, "index") <- idx[s]
    class(x) <- oc
    x
}
```

So it'd be easy to drop the low-frequency haplotypes, eg, to select only the haplotypes present 10 or more times:

``` r
h <- haplotype(.....
h10 <- subset(h, 10)
```

The function can have additional arguments, for instance to remove haplotypes with two many missing/ambiguous nucleotides.

**Comment by jhmarcus** [comment]
Great. Thank you so much @emmanuelparadis!

**Comment by emmanuelparadis** [comment]
I'm adding this function in pegas/R.

**Comment by santimo** [comment]
Is this function available?
I can see it in the help file but I can't call it.
I have pegas 0.11 installed
> library(pegas)
> haplo_trnsg_psba_n2<-subset.haplotype(trnsg_psba, minfreq=2)
Error in subset.haplotype(trnsg_psba, minfreq = 2) : 
  could not find function "subset.haplotype"

Thanks very much

**Comment by emmanuelparadis** [comment]
yes but it is not exported. So do: `haplo_trnsg_psba_n2 <- subset(trnsg_psba, minfreq = 2)`
