### ISSUE TITLE
Make adegenet a Suggests package?

### ISSUE THREAD

**Issue by privefl** [emmanuelparadis/pegas#62]
Would it be possible to make {adegenet} a Suggests package?
It has so many dependencies to install, which is a trouble for many users that want to use {pegas} without using {adegenet}.

**Comment by emmanuelparadis** [comment]
That's possible. Two functions from adegenet are actually used (imported) in pegas: `df2genind` and `genind2df`. I think they are less used nowadays. adegenet was moved from "Depends" to "Imports" a couple of months ago.

Let's see if there are other opinions on this question.

**Comment by emmanuelparadis** [comment]
I pushed a new version here with the proposed change.

**Comment by privefl** [comment]
Great, thanks
