### ISSUE TITLE
Problem ploting haplonet with mutations as dots (show.mutation=2)

### ISSUE THREAD

**Issue by Juanphg** [emmanuelparadis/pegas#63]
Hello,
First I would like to thank for pegas and ape, really makes easy analyzing and ploting the data. 
Now, I'm using pegas to plot a haploNet, but I'm having an issue when trying to plot the mutations as dots, I get a plot but without the pies:
This is the command: 
`plot(hmgb.sc.net, size=attr(hmgb.sc.net,'freq'), show.mutation=2,labels =F, scale.ratio=10, 
     pie = hmgb.sc.ind.hap, xy=hmgb.cs.XY, bg=colors.hmgb.sc)`
this is the error I get: 
`Error in .labelSegmentsHaploNet(xx, yy, altlink[s, 1:2, drop = FALSE],  : 
  argument "scale.ratio" is missing, with no default`
but as you see in the plot command I'm specifying `scale.ratio`. I also tried with different values for the parameter but it did not work. 
This is the plot: 
![image](https://user-images.githubusercontent.com/66382504/139713943-78fdbe0e-64d1-4745-be00-dbc357774617.png)

This is the plot when I change the mutation to the default value, `show.mutation=1`. I want to change to dots because in this case, the bars are too wide.
![image](https://user-images.githubusercontent.com/66382504/139714431-01fd5f17-fa9a-4f9e-9684-64b50afc360c.png)

Thanks in advance for your help, 
Kind regards, 
Juan Pablo

**Comment by emmanuelparadis** [comment]
Hi. Thanks for the appreciation!
Did you install the version of pegas from GitHub? I fixed a bug recently about `scale.ratio`. You can type in R `packageVersion("pegas")`. The version on CRAN is 1.0.1. The version 1.0.2 has some bug fixes.
Cheers,

**Comment by Juanphg** [comment]
Thanks for your help. I downloaded the file form github and now I have the version 1.0.3. It worked without problem. 
Cheers,
