### ISSUE TITLE
Adding the pairwise deletion argument to the dist.asd () function

### ISSUE THREAD

**Issue by DenisGoryunov** [emmanuelparadis/pegas#65]
Hello,

 Could you please consider the possibility to implement pairwise deletion argument for the dist.asd () function? 

Regards,
Denis

**Comment by emmanuelparadis** [comment]
Done. Note also the new function `nullAlleles2NA` to change genotypes with null allele(s) into `NA`. The help pages have been updated.
Pushed here as pegas 1.1-3.

**Comment by DenisGoryunov** [comment]
Dear Dr. Paradis,
Thank you so much! I'll try it soon. Is the new version available on the CRAN website?

Regards,
Denis

**Comment by emmanuelparadis** [comment]
Dear Denis,
Not yet. You'll have to install from GH.
Cheers,
