### ISSUE TITLE
Computing the frequencies of haplotypes for each population from "loci" objects

### ISSUE THREAD

**Issue by awshort** [emmanuelparadis/pegas#67]
Dear Emmanuel, 

Sorry to bother you with more questions about getting information from loci objects as I know the functions for "loci" objects are still in development. However, I am trying to color the haplotype symbols in my plot based on the haplotype frequencies for each population from my "loci" object and I wanted to ask whether you know of a way to compute the frequencies of haplotypes for each population from a "loci" object like the haploFreq function does for "DNAbin" objects?

Thank you for your help!

Sincerely,
Aidan Short

**Comment by emmanuelparadis** [comment]
Dear Aidan,
There's no direct tool/function to do this (as I know). One difficulty is that for diploid data, a single individual may have two haplotypes, so you need to duplicate the population variable.

**Comment by awshort** [comment]
Dear Emmanuel,

Got it, I figured that might be the case. Thank you for your response! I will try a few things and if I figure something out I will post it here just in case anyone else has the same question. 

Thank you!

Aidan
