### ISSUE TITLE
 The link to fstat in pegas Fst help is no longer valid

### ISSUE THREAD

**Issue by thibautjombart** [emmanuelparadis/pegas#7]
The link to fstat in pegas Fst help is no longer valid - fstat has moved from adegenet to hierfstat.

**Comment by thibautjombart** [comment]
This is coming from:
https://github.com/thibautjombart/adegenet/issues/62

**Comment by emmanuelparadis** [comment]
Thanks for pointing this out. It's corrected and I pushed on GH. I guess it's best that I wait for adegenet to be ready for CRAN before submitting pegas (will surely be 0.8-1).

**Comment by thibautjombart** [comment]
It is ready! =D
We are just giving a few days for packages depending on adegenet to get up
to date. But the current master will not change.

On Wed, Jun 24, 2015 at 12:51 PM, Emmanuel Paradis <notifications@github.com

**Comment by emmanuelparadis** [comment]
I've just submitted pegas 0.8-1 on CRAN. Just wait (everything's going to be fine ;) )

**Comment by thibautjombart** [comment]
Awesome!
Fingers crossed.

**Comment by emmanuelparadis** [comment]
On CRAN now.
