### ISSUE TITLE
Known haplotype frequencies

### ISSUE THREAD

**Issue by Timzladen** [emmanuelparadis/pegas#70]
Hi Emmanuel,
I have a set of sequences derived from metabarcoding that I want to use to reconstruct a haplotype network. However, I encountered a problem, since the sequences all return unique haplotypes when processed with the haplotype function. Now this is not a surprise, since my set was denoised and clustered essentially producing 97% OTUs. But I would still like to see the representation of each OTU in a pie chart format with the haplonet function. However, I don't see to find a way to introduce the individual OTU frequencies into the picture. Some OTUs are way more abundant than others and I would like to compare the metabarcoding haplotype network to a haplotype network I have generated with specimens I collected in the field. Essentially, I would like to join a phylogenetic tree and a heatmap of occurrences in different samples into a haplotype network. 

So can you recommend me a way to introduce the haplotype frequencies as prior knowledge for haplonet generation?

**Comment by emmanuelparadis** [comment]
Hi Tim,
Did you see the option `pie` in `plot.haploNet`? You may have a look at the function `haploFreq` too (although I'm not sure).
See also `vignette("PlotHaploNet")` where there some additional info on plotting haplotypes.
Emmanuel
