### ISSUE TITLE
Error Reading In Fasta Data

### ISSUE THREAD

**Issue by sbabbbie** [emmanuelparadis/pegas#79]
This might be a really basic issue but I'm not very good with R. I'm trying to load in a fasta file using adegenet following the tutorial on page 25 of the manual. But when I run the code equivalent to:

fl <- system.file("files/pdH1N1-NA.fasta", package = "adegenet")

I get the following error:

Error in readBin(file, "raw", file.size(file)) : 
  can only read from a binary connection
In addition: Warning message:
In file(con, "rb") :
  file("") only supports open = "w+" and open = "w+b": using the former

I can tell the second issue is to do with permissions and I can fix that, but I have no idea what the first readBin issue is.

**Comment by emmanuelparadis** [comment]
What are your commands?
Here're mine:
```r
R> library(ape)
R> fl <- system.file("files/pdH1N1-NA.fasta", package = "adegenet")
R> fl
[1] "/usr/local/lib/R/site-library/adegenet/files/pdH1N1-NA.fasta"
R> x <- read.FASTA(fl)
R> x
433 DNA sequences in binary format stored in a list.

All sequences of same length: 1353 

Labels:
GQ243758
GQ160610
GQ243752
GQ243762
GQ243756
GQ368663
...

Base composition:
    a     c     g     t 
0.315 0.186 0.239 0.260 
(Total: 585.85 kb)
```
