### ISSUE TITLE
A dist.asd function warning with pairwise.deletion = TRUE parameter

### ISSUE THREAD

**Issue by DenisGoryunov** [emmanuelparadis/pegas#91]
Dear Dr. Paradis,

I encountered an issue when ran the comand using **Pegas 1.3** :

`m=dist.asd(my_snp, pairwise.deletion = TRUE)`

**```
Warning message:
In D/nloc : longer object length is not a multiple of shorter object length
```**
Could you advise me please how i can fix the issue?

Regards,
Denis

**Comment by emmanuelparadis** [comment]
Dear Denis,

I think I've fixed this bug. Please try to install the latest development version from here (ver. 1.3-0.3).

Best,

Emmanuel

**Comment by DenisGoryunov** [comment]
Dear Dr. Paradis,
Thank you so much! I'm wondering if binaries are available for the latest development version (ver. 1.3-0.3) or i have to compile it from source using Rtools? I downloaded **pegas-master.zip** containing the version but can not figure out how to install it to **RStudio**.

Regards,
Denis

**Comment by DenisGoryunov** [comment]
Dear Dr. Paradis,

I managed installation of the latest development version for **Pegas** package. The issue in **dist.asd()** has been fixed.

Many thanks,
Denis
